// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Response struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Attention            int64    `protobuf:"varint,2,opt,name=attention,proto3" json:"attention,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	PromotionId          int64    `protobuf:"varint,5,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	Sex                  int64    `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Beans                int64    `protobuf:"varint,7,opt,name=beans,proto3" json:"beans,omitempty"`
	Phonenumber          string   `protobuf:"bytes,8,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Addtime              string   `protobuf:"bytes,9,opt,name=addtime,proto3" json:"addtime,omitempty"`
	Addip                string   `protobuf:"bytes,10,opt,name=addip,proto3" json:"addip,omitempty"`
	Logintime            string   `protobuf:"bytes,11,opt,name=logintime,proto3" json:"logintime,omitempty"`
	Loginip              string   `protobuf:"bytes,12,opt,name=loginip,proto3" json:"loginip,omitempty"`
	Logintimes           int64    `protobuf:"varint,13,opt,name=logintimes,proto3" json:"logintimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetAttention() int64 {
	if m != nil {
		return m.Attention
	}
	return 0
}

func (m *Response) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Response) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Response) GetPromotionId() int64 {
	if m != nil {
		return m.PromotionId
	}
	return 0
}

func (m *Response) GetSex() int64 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *Response) GetBeans() int64 {
	if m != nil {
		return m.Beans
	}
	return 0
}

func (m *Response) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

func (m *Response) GetAddtime() string {
	if m != nil {
		return m.Addtime
	}
	return ""
}

func (m *Response) GetAddip() string {
	if m != nil {
		return m.Addip
	}
	return ""
}

func (m *Response) GetLogintime() string {
	if m != nil {
		return m.Logintime
	}
	return ""
}

func (m *Response) GetLoginip() string {
	if m != nil {
		return m.Loginip
	}
	return ""
}

func (m *Response) GetLogintimes() int64 {
	if m != nil {
		return m.Logintimes
	}
	return 0
}

type Requestlist struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Ob                   string   `protobuf:"bytes,2,opt,name=ob,proto3" json:"ob,omitempty"`
	PromotionId          int64    `protobuf:"varint,3,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Requestlist) Reset()         { *m = Requestlist{} }
func (m *Requestlist) String() string { return proto.CompactTextString(m) }
func (*Requestlist) ProtoMessage()    {}
func (*Requestlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Requestlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requestlist.Unmarshal(m, b)
}
func (m *Requestlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requestlist.Marshal(b, m, deterministic)
}
func (m *Requestlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requestlist.Merge(m, src)
}
func (m *Requestlist) XXX_Size() int {
	return xxx_messageInfo_Requestlist.Size(m)
}
func (m *Requestlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Requestlist.DiscardUnknown(m)
}

var xxx_messageInfo_Requestlist proto.InternalMessageInfo

func (m *Requestlist) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Requestlist) GetOb() string {
	if m != nil {
		return m.Ob
	}
	return ""
}

func (m *Requestlist) GetPromotionId() int64 {
	if m != nil {
		return m.PromotionId
	}
	return 0
}

type Responselist struct {
	Userlist             []*Response `protobuf:"bytes,1,rep,name=userlist,proto3" json:"userlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Responselist) Reset()         { *m = Responselist{} }
func (m *Responselist) String() string { return proto.CompactTextString(m) }
func (*Responselist) ProtoMessage()    {}
func (*Responselist) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *Responselist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Responselist.Unmarshal(m, b)
}
func (m *Responselist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Responselist.Marshal(b, m, deterministic)
}
func (m *Responselist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Responselist.Merge(m, src)
}
func (m *Responselist) XXX_Size() int {
	return xxx_messageInfo_Responselist.Size(m)
}
func (m *Responselist) XXX_DiscardUnknown() {
	xxx_messageInfo_Responselist.DiscardUnknown(m)
}

var xxx_messageInfo_Responselist proto.InternalMessageInfo

func (m *Responselist) GetUserlist() []*Response {
	if m != nil {
		return m.Userlist
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.user.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.user.Response")
	proto.RegisterType((*Requestlist)(nil), "go.micro.srv.user.Requestlist")
	proto.RegisterType((*Responselist)(nil), "go.micro.srv.user.Responselist")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x41, 0x6e, 0xdb, 0x30,
	0x10, 0xac, 0x24, 0xdb, 0x92, 0x56, 0x6e, 0xd1, 0x12, 0x45, 0xc1, 0xaa, 0x85, 0xab, 0xea, 0xe4,
	0x93, 0x0e, 0xee, 0xa1, 0x1f, 0x28, 0x60, 0x14, 0x28, 0x7a, 0x10, 0x92, 0x73, 0x40, 0x99, 0x84,
	0x43, 0xc4, 0x22, 0x15, 0x92, 0x36, 0xf2, 0x98, 0x7c, 0x2e, 0x3f, 0x09, 0xb8, 0x96, 0x65, 0x23,
	0x4e, 0x7c, 0xdb, 0x99, 0xd9, 0x1d, 0x92, 0xc3, 0x05, 0xd8, 0x5a, 0x61, 0xaa, 0xce, 0x68, 0xa7,
	0xc9, 0xa7, 0xb5, 0xae, 0x5a, 0xb9, 0x32, 0xba, 0xb2, 0x66, 0x57, 0x79, 0xa1, 0xfc, 0x0a, 0x71,
	0x2d, 0xee, 0xb7, 0xc2, 0x3a, 0xf2, 0x01, 0x42, 0xc9, 0x69, 0x50, 0x04, 0xf3, 0xa8, 0x0e, 0x25,
	0x2f, 0x9f, 0x42, 0x48, 0x6a, 0x61, 0x3b, 0xad, 0xac, 0x78, 0x29, 0x92, 0xef, 0x90, 0x32, 0xe7,
	0x84, 0x72, 0x52, 0x2b, 0x1a, 0x22, 0x7d, 0x24, 0x48, 0x0e, 0x89, 0x92, 0xab, 0x3b, 0xc5, 0x5a,
	0x41, 0xa3, 0x22, 0x98, 0xa7, 0xf5, 0x80, 0xc9, 0x17, 0x98, 0xb0, 0x1d, 0x73, 0xcc, 0xd0, 0x11,
	0x2a, 0x3d, 0x22, 0x3f, 0x61, 0xda, 0x19, 0xdd, 0x6a, 0x6f, 0x70, 0x23, 0x39, 0x1d, 0xa3, 0x69,
	0x36, 0x70, 0x7f, 0x39, 0xf9, 0x08, 0x91, 0x15, 0x0f, 0x74, 0x82, 0x8a, 0x2f, 0xc9, 0x67, 0x18,
	0x37, 0x82, 0x29, 0x4b, 0x63, 0xe4, 0xf6, 0x80, 0x14, 0x90, 0x75, 0xb7, 0x5a, 0x09, 0xb5, 0x6d,
	0x1b, 0x61, 0x68, 0x82, 0xe7, 0x9c, 0x52, 0x84, 0x42, 0xcc, 0x38, 0x77, 0xb2, 0x15, 0x34, 0x45,
	0xf5, 0x00, 0xbd, 0x23, 0xe3, 0x5c, 0x76, 0x14, 0x90, 0xdf, 0x03, 0xff, 0xdc, 0x8d, 0x5e, 0x4b,
	0x85, 0x13, 0x19, 0x2a, 0x47, 0xc2, 0xbb, 0x21, 0x90, 0x1d, 0x9d, 0xee, 0xdd, 0x7a, 0x48, 0x66,
	0x00, 0x43, 0x9b, 0xa5, 0xef, 0xf1, 0x92, 0x27, 0x4c, 0x79, 0x05, 0x59, 0x1f, 0xff, 0x46, 0x5a,
	0x47, 0x08, 0x8c, 0x3a, 0xb6, 0x16, 0x7d, 0xce, 0x58, 0xfb, 0xe4, 0x75, 0x83, 0x11, 0xa7, 0x75,
	0xa8, 0x9b, 0xb3, 0x9c, 0xa2, 0xb3, 0x9c, 0xca, 0x25, 0x4c, 0x0f, 0x1f, 0x87, 0xb6, 0xbf, 0x21,
	0xf1, 0x9f, 0xed, 0x6b, 0x1a, 0x14, 0xd1, 0x3c, 0x5b, 0x7c, 0xab, 0xce, 0x56, 0xa1, 0x3a, 0x8c,
	0xd4, 0x43, 0xf3, 0xe2, 0x31, 0x80, 0xd1, 0xb5, 0x15, 0x86, 0xfc, 0x81, 0x78, 0x29, 0x1c, 0x96,
	0xf9, 0xab, 0xa3, 0xf8, 0x86, 0xfc, 0x92, 0x6d, 0xf9, 0x8e, 0xfc, 0x87, 0xac, 0x77, 0xf9, 0xe7,
	0xaf, 0x35, 0x7b, 0xdb, 0xc9, 0x9f, 0x9e, 0xff, 0xb8, 0xe0, 0xe6, 0x1b, 0x9a, 0x09, 0xae, 0xf5,
	0xaf, 0xe7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x62, 0xcf, 0xf1, 0xe4, 0x02, 0x00, 0x00,
}
