package main

import (
	dept "gin-t/api/dept/controller"
	member "gin-t/api/member/controller"
	_ "gin-t/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title gin测试api
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @basePath /api/v1
// @host localhost:8000

func main() {
	r := gin.Default()
	v1 := r.Group("/api/v1")
	{
		member := member.New()
		m := v1.Group("/member")
		{
			m.GET("/account", member.Account)
		}
		dept := dept.New()
		d := v1.Group("/dept")
		{
			d.GET("/getdeptone", dept.GetDeptOne)
		}
		// m2 := v1.Group("/member2")
		// {
		// 	m2.GET("", member2.Index2)
		// 	m2.GET("/account", member2.ShowAccount2)
		// }
		// v1.GET("/ping", func(c *gin.Context) {
		// 	c.JSON(200, gin.H{
		// 		"message": "pong",
		// 	})
		// })
	}
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.Run(":8000") // listen and serve on 0.0.0.0:8080
}

func init() {
	gorm.DefaultTableNameHandler = func(db *gorm.DB, defaultTableName string) string {
		return "mt_" + defaultTableName
	}
	// gorm.Logger
}
